name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t shyleshraj/lookup-frontend:latest .

      - name: Push Docker image
        run: |
          docker push shyleshraj/lookup-frontend:latest

      - name: Deploy to Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | heroku container:login
          docker tag shyleshraj/lookup-frontend:latest registry.heroku.com/your-frontend-app-name/web
          docker push registry.heroku.com/your-frontend-app-name/web
          heroku container:release web -a your-frontend-app-name
