name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t shyleshraj/lookup-frontend:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push shyleshraj/lookup-frontend:latest

      - name: Login to Heroku
        uses: akshnz/heroku-docker-action@v0.1.0
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Set Heroku remote
        run: git remote add heroku https://git@heroku.com/<your-heroku-app-name>.git

      - name: Deploy to Heroku
        run: |
          git push heroku master
